name: Update Base docker image

on:
  workflow_dispatch:
  push:
    branches:
      - feature/base-image

env:
    HOST: app@${{ secrets.DEV_HOST_IP }}
    PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}

jobs:

  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        docker build -t base-image -f ./base-image.dockerfile .
        docker save base-image > ${{ github.event.repository.name }}-base-image.tar

    - name: Saving base docker image to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: base-docker-image
        path: |
          ${{ github.event.repository.name }}-base-image.tar
        retention-days: 90
