name: Update Base docker image

on:
  workflow_dispatch:
  push:
    branches: dev

env:
    HOST: app@${{ secrets.DEV_HOST_IP }}
    PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}

jobs:

  build:
    runs-on: ubuntu-latest
    environment: ${{ vars.GITHUB_BASE_REF }}
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        docker build -t base-image -f ./base-image.dockerfile .
        docker save base-image > base-image-${{ vars.GITHUB_BASE_REF	 }}.tar
        ls -1

    - name: Saving base docker image to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: base-image
        path: |
          base-image-${{ vars.GITHUB_BASE_REF }}.tar
        retention-days: 1
