name: DEV | Build and Deploy

on:
  push:
    branches:
      - dev
      - feature/base-image

env:
    HOST: app@${{ secrets.DEV_HOST_IP }}
    PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
    ENV_FILE: ${{ secrets.DEV_ENV_FILE }}
    SA_FILE: ${{ secrets.SA_FILE }}
    ENVIRONMENT: dev
    BACKEND_PORT: 5010
    FRONTEND_PORT: 3010

jobs:

  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: workflow_name.yml
        branch: master
        name: base-docker-image
        path: extract_here
        if_no_artifact_found: fail

    - name: Build the Docker image
      run: |
        docker build -t ${{ github.event.repository.name }}-$ENVIRONMENT . --no-cache
        docker save ${{ github.event.repository.name }}-$ENVIRONMENT > ${{ github.event.repository.name }}.tar
        ls -1

    - name: Saving docker image to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: |
          ${{ github.event.repository.name }}.tar
        retention-days: 2

  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Restoring docker image from artifacts
      uses: actions/download-artifact@v3
      with:
        name: docker-image

    - name: Uploading artifact to the server
      run: |
        which rsync || ( apt-get update -y && apt-get install rsync -y )
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        eval $(ssh-agent -s)
        echo "${PRIVATE_SSH_KEY}" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        echo "FAILING ${{ github.event.repository.name }}-${ENVIRONMENT}:*"
        ssh ${HOST} docker image rm -f $(docker images --filter=reference="${{ github.event.repository.name }}-${ENVIRONMENT}:*" -q) || true
        echo "${ENV_FILE}" > .env
        echo "${SA_FILE}" > sa.json
        git clone https://github.com/ALLATRA-IT/cloudobs-infrastructure.git --depth 1
        cp cloudobs-infrastructure/shared/files/docker-compose.yml .
        printf "ENVIRONMENT=${ENVIRONMENT}\nBACKEND_PORT=${BACKEND_PORT}\nFRONTEND_PORT=${FRONTEND_PORT}" > .compose.env
        ls -1a
        rsync -a -v --progress --delete --quiet .env sa.json .compose.env docker-compose.yml ${{ github.event.repository.name }}.tar ${HOST}:~/${ENVIRONMENT}/
        ssh ${HOST} "docker load --input ~/${ENVIRONMENT}/${{ github.event.repository.name }}.tar && mkdir -p ~/${ENVIRONMENT}"
        ssh ${HOST} "cd ~/${ENVIRONMENT} && docker compose down && docker compose --env-file .compose.env up -d && sleep 10 && docker compose ps"
