name: DEV | Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - feature/base-image

env:
    HOST: app@${{ secrets.DEV_HOST_IP }}
    PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
    ENV_FILE: ${{ secrets.DEV_ENV_FILE }}
    SA_FILE: ${{ secrets.SA_FILE }}
    ENVIRONMENT: dev
    BACKEND_PORT: 5010
    FRONTEND_PORT: 3010

jobs:

  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # - name: Download artifact
    #   id: download-artifact
    #   uses: dawidd6/action-download-artifact@v2
    #   with:
    #     workflow: base-image.yml
    #     name: base-image
    #     if_no_artifact_found: fail

    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build the Docker image
    #   run: |
    #     docker load --input base-image.tar
    #     docker images
    #     docker build -t ${{ github.event.repository.name }}-${ENVIRONMENT} . --no-cache
    #     docker save ${{ github.event.repository.name }}-$ENVIRONMENT > ${{ github.event.repository.name }}.tar

    - name: Cloning Infrastructure Repository
      uses: actions/checkout@master
      with:
        repository: ALLATRA-IT/cloudobs-infrastructure
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        path: 'cloudobs-infrastructure'
        fetch-depth: '1'

    - name: Uploading artifact to the server
      run: |
        echo "STEP [01]"
        ls -1
        echo "STEP [02]"
        cp cloudobs-infrastructure/shared/files/docker-compose.yml .
        echo "STEP [03]"
        docker images | grep cloudobs
        echo "STEP [04]"
        which rsync || ( apt-get update -y && apt-get install rsync -y )
        echo "STEP [05]"
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        echo "STEP [06]"
        eval $(ssh-agent -s)
        echo "STEP [07]"
        echo "${PRIVATE_SSH_KEY}" | tr -d '\r' | ssh-add - > /dev/null
        echo "STEP [08]"
        mkdir -p ~/.ssh
        echo "STEP [09]"
        chmod 700 ~/.ssh
        echo "STEP [10]"
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        echo "STEP [11]"
        echo "${ENV_FILE}" > .env
        echo "STEP [12]"
        echo "${SA_FILE}" > sa.json
        echo "STEP [13]"
        printf "ENVIRONMENT=${ENVIRONMENT}\nBACKEND_PORT=${BACKEND_PORT}\nFRONTEND_PORT=${FRONTEND_PORT}" > .compose.env
        rsync -a -v --progress --delete --quiet .env sa.json .compose.env docker-compose.yml ${{ github.event.repository.name }}.tar ${HOST}:~/${ENVIRONMENT}/
        echo "STEP [01]"
        ssh ${HOST} docker image rm -f $(docker images --filter=reference="${{ github.event.repository.name }}-${ENVIRONMENT}" -q) || true
        ssh ${HOST} "docker load --input ~/${ENVIRONMENT}/${{ github.event.repository.name }}.tar && mkdir -p ~/${ENVIRONMENT}"
        ssh ${HOST} "cd ~/${ENVIRONMENT} && docker compose down && docker compose --env-file .compose.env up -d && sleep 10 && docker compose ps"
